
EXPLAIN SELECT * FROM READERS
        WHERE FIRSTNAME = 'John';

CREATE INDEX FIRSTNM ON READERS (FIRSTNAME);
CREATE INDEX LASTNM ON READERS (LASTNAME);
CREATE INDEX TITL ON BOOKS (TITLE);

EXPLAIN SELECT * FROM READERS
        WHERE FIRSTNAME = 'John';
