ALTER TABLE BOOKS ADD BESTSELLER BOOL DEFAULT 0;

DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE RENT_COUNT, BK_ID INT;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN ALL_BOOKS;
    WHILE (FINISHED = 0) DO
            FETCH ALL_BOOKS INTO BK_ID;
            IF (FINISHED = 0) THEN
                SELECT COUNT(*) FROM RENTS
                WHERE BOOK_ID = BK_ID
                INTO RENT_COUNT;
                UPDATE BOOKS SET BESTSELLER = 1
                WHERE BOOK_ID = BK_ID AND RENT_COUNT > 2;
                COMMIT;
            END IF;
        END WHILE;
    CLOSE ALL_BOOKS;
END $$

DELIMITER ;