
USE kodilla_course;

CREATE TABLE STATS (
    STAT_ID INT(11) AUTO_INCREMENT,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL,
    PRIMARY KEY (STAT_ID)
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS BESTSELLERS FROM BOOKS
WHERE BESTSELLER = 1;

CREATE EVENT UPDATE_STATS_BESTSELLERS
ON SCHEDULE EVERY 1 MINUTE
DO BEGIN
    CALL UpdateBestsellers();
    INSERT INTO STATS(STAT_DATE, STAT, VALUE)
    VALUES(CURRENT_TIMESTAMP, 'BESTSELLERS', (SELECT * FROM BESTSELLERS_COUNT));
END;
